### ISSUE TITLE
why would I use this?

### ISSUE THREAD

**Issue by jeraldpunx** [HubSpot/youmightnotneedjquery#203]
in JQUERY only this line. so ez, no need to hassle.
`$(el).fadeIn();`

while this, 
function fadeIn(el) {
  el.style.opacity = 0;

 ```
 var last = +new Date();
  var tick = function() {
    el.style.opacity = +el.style.opacity + (new Date() - last) / 400;
    last = +new Date();

    if (+el.style.opacity < 1) {
      (window.requestAnimationFrame && requestAnimationFrame(tick)) || setTimeout(tick, 16);
    }
  };
  tick();
}
fadeIn(el);
```
takes a long line of code.

**Comment by Abbondanzo** [comment]
The idea is that you won't need to carry around 240KB of luggage just to accomplish an effect that can be produced in a file that is only 360 bytes (the code you've listed above). This documentation is here to provide alternatives and recommendations so that you don't bloat your own library with tools you won't end up using.

If animations are all you need, this can just as easily be accomplished with a simple css class:
```css
@keyframes fadeIn {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

.fadeIn {
  animation-name: fadeIn;
}
```
